FROM node:22.21-alpine
WORKDIR /app
RUN npx create-react-app . --template minimal --skip-git
COPY src/ ./src/
RUN npm run build
RUN npm install -g serve
EXPOSE 8080
CMD ["serve", "-s", "build", "-l", "8080"]
